language: go

go:
  - 1.7.5
  - 1.8
  - tip

branches:
  only:
    - master

before_install:
  - go get github.com/mattn/goveralls

install:
  - go version
  - go env

script:
  - go vet -v .
  - $HOME/gopath/bin/goveralls -service=travis-ci
